name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sed -i -e '/"minimum-stability"/d' composer.json && composer update --lock

      - run: composer require nunomaduro/larastan --with-dependencies --dev
