name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          composer install
          composer remove laravel/sanctum laravel/tinker
          composer remove --dev laravel/sail

      - run: composer require nunomaduro/larastan --with-all-dependencies --dev
